# syntax=docker/dockerfile:1

FROM node:20-bullseye
# Set NODE_ENV to development
ENV NODE_ENV=development

WORKDIR /usr/src/app

# Copy package.json and lock file
COPY package*.json ./

# Install ALL dependencies (including dev)
RUN npm install

# Copy the rest of the code
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Run dev server
CMD ["npm", "run", "dev", "--", "--host"]
