services:
  node-backend:
    build:
      context: ./node-backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}  
    ports:
      - 3001:3000
    volumes:
      - ./node-backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./node-backend/certs:/usr/src/app/certs:ro
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

  python-backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_BACKEND_URL=${NODE_BACKEND_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "5001:5000"
    volumes:
      - ./python_backend:/usr/src/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8081:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - node-backend
      - python-backend
    restart: unless-stopped

volumes:
  node_modules:

