[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]

ignore = [
  "D100",  
  "D101",  
  "D102", 
  "D103",  
  "D104", 
  "D203",
  "D213", 
  "COM812", 
  "ISC001",
  "S608", 
  "S311",
  "PERF203",
  "ANN202",
  "BLE001",
]

[tool.ruff.lint.per-file-ignores]
"python_backend/tests/**/*.py" = [
    "S101",
    "PLR0913",
    "FBT003",
    "FBT001",
    "ANN401",
]

[tool.bandit]
skips = ["S608"]



