# fly.toml app configuration file generated for node-backend-proud-wildflower-5990 on 2025-05-28T19:09:27+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'node-backend-proud-wildflower-5990'
primary_region = 'syd'


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "requests"
  soft_limit = 100
  hard_limit = 200

[[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "get"
    path = "/api/ping"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
