# Use the official Playwright base image with Python 3.11 and all browsers pre-installed
FROM mcr.microsoft.com/playwright/python:v1.51.0-jammy

# Set working directory
WORKDIR /usr/src/app

# Copy requirements first for caching
COPY requirements.txt .
COPY requirements-dev.txt .

# Install python dependencies
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy all source files including certs folder
COPY . .

# Expose the port your FastAPI app listens on
EXPOSE 5000

# Command to run your python FastAPI app via uvicorn
CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
