# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /usr/src/app

# Copy requirements first for caching
COPY requirements.txt .
COPY requirements-dev.txt .

# Install python dependencies
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy all source files including certs folder
COPY . .

# Expose the port your FastAPI app listens on
EXPOSE 5000

# Command to run your python FastAPI app via uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
