name: Daily Scrape Trigger

on:
  schedule:
    - cron: '00 13 * * *'  # runs daily at midnight
  workflow_dispatch:    

jobs:
  trigger_scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Python backend daily scrape
        run: |
          curl -X GET https://python-backend-cold-feather-2329.fly.dev/cron-daily-scrape \
            -H "Authorization: Bearer $BEARER_TOKEN"
