name: Deploy Python Backend to Fly.io

on:
  push:
    branches: 
      - main 
    paths:
      - 'python-backend/**'

jobs:
  deploy:
    name: Deploy python backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        working-directory: python_backend
        run: flyctl deploy --remote-only 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PYTHON_BACKEND }}
