name: CI on Push

on:
  push:
    branches: 
      - main 
    paths:
      - 'python_backend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: python_backend
        run: |
          pip install -r requirements.txt
          pip install pytest ruff mypy

      - name: Check style
        working-directory: python_backend
        run: ruff check .
        
      - name: Run unit tests
        working-directory: python_backend
        run: pytest tests/unit
        
