name: Scraper Healthcheck

on:
  schedule:
    - cron: '00 8 * * *' 

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    defaults:
      run:
        working-directory: python-backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: python_backend
        run: |
          pip install -r requirements-dev.txt
          pip install pytest

      - name: Run unit tests
        working-directory: python_backend
        run: pytest tests/unit

      - name: Run scraper integration test
        working-directory: python_backend
        run: pytest tests/integration/pages/test_sucess_one_page.py
